### ISSUE TITLE
Bug: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alessioalex** [mcollina/fastfall#3]
While integrating `fastfall` into the benchmark for `waterfallize` I used the following example (the one from the readme):

``` js
fall([
  function a (cb) {
    cb(null, 'a')
  },
  function b (a, cb) {
    cb(null, 'a', 'b')
  },
  function c (a, b, cb) {
    cb(null, 'a', 'b', 'c')
  }
], function result (err, a, b, c) {
  done();
})
```

If you run this a lot of times (say 100.000 like in `bench.js`) you'll get this error:

``` bash
 alessio: /home/alessio/www/fastfall git:master
→ node bench.js 
/home/alessio/www/fastfall/fall.js:89
    var args = []
    ^
RangeError: Maximum call stack size exceeded
    at Holder.work (/home/alessio/www/fastfall/fall.js:89:5)
    at fall (/home/alessio/www/fastfall/fall.js:45:13)
    at benchFastFall (/home/alessio/www/fastfall/bench.js:61:3)
    at end (/home/alessio/www/fastfall/bench.js:19:7)
    at result (/home/alessio/www/fastfall/bench.js:71:5)
    at work (/home/alessio/www/fastfall/fall.js:102:21)
    at c (/home/alessio/www/fastfall/bench.js:69:5)
    at work (/home/alessio/www/fastfall/fall.js:97:31)
    at b (/home/alessio/www/fastfall/bench.js:66:5)
    at work (/home/alessio/www/fastfall/fall.js:97:31)
```

**Comment by mcollina** [comment]
That's perfectly normal, as these calls are not async, and are used there for 'demo' purpose. `fastfall` is build to run async functions.

**Comment by mcollina** [comment]
One thing that you can do to fix your bench, is to put the `done` callback in a `setImmediate`call.

**Comment by mcollina** [comment]
You are creating a new stack here: https://github.com/alessioalex/waterfallize/blob/master/index.js#L17-L24.

In async.waterfall it's here: https://github.com/caolan/async/blob/master/lib/async.js#L713.

Basically `fastfall` will not make your function run asynchronously if there is no need to.

**Comment by alessioalex** [comment]
@mcollina thanks, I should have put async functions in the benchmark, don't know how I've missed that.
